services:
  - type: web
    runtime: static
    name: adranna-systems-app
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
